hi link wTitle Constant
sy match wTitle /\v\~.*\~/
hi link wSubtitle WarningMsg
sy match wSubtitle /\v\~\~.*\~\~/
hi link wSubsubtitle Comment
sy match wSubsubtitle /\v\~\~\~.*\~\~\~/
hi link wPath Error
sy match wPath /\v\.\/\f{3,}/
hi link wEnd LineNr
sy match wEnd /\v^:::/
